name: Siyam
favicon: null
layout_spectrum: 0.7095522943418473
typography_spectrum: 0.2802059904206544
title: Fashion Illustrator
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#ededed'
    - '#393939'
    - '#8f8f8f'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
