name: Siyam
favicon: null
layout_spectrum: 0.7095522943418473
typography_spectrum: 0.2802059904206544
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#545454'
    - '#2b2b2b'
    - '#030303'
  brandStrength: 0.5
  lightness: 0.2398448616731912
  saturation: 0.3139517104718834
  rhythmicContrast: 0.5770104289986193
purpose: []
