typography_spectrum: 0.48466
content_rating:
  adult: false
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#ededed'
    - '#393939'
    - '#8f8f8f'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24639
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/910f011b-f0aa-41a8-bf7b-aaf4e3e9749d.png
name: SIYAM ILLUSTRATION
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: about us
    url: about us
    type: external
favicon: null
title: ''
purpose: []
